modLoader = "javafml"
loaderVersion = "[4,)"
displayURL = "https://github.com/HappyRespawnanchor/no-blocked-servers"
issueTrackerURL = "https://github.com/HappyRespawnanchor/no-blocked-servers/issues"
license = "WTFPL"

[[mods]]
modId = "no_blocked_servers"
version = "${version}"
displayName = "No Blocked Servers"
authors = "HappyRespawnanchor"
description = '''
Join a server that has been blocked by Mojang for violating Minecraft EULA.
'''
side = "CLIENT"
logoFile = "no_blocked_server_logo.png"

[[dependencies.no_blocked_servers]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.no_blocked_servers]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "no_blocked_servers-common.mixins.json"
